name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Streamlit to verify the app (optional for debugging)
      - name: Run Streamlit (optional)
        run: streamlit run index.py --server.headless true
